// GENERATED BY COMPUTER, DO NOT EDIT.
typedef unsigned long long INT_PTR, *PINT_PTR;
typedef INT_PTR (*FARPROC)();
typedef void *HMODULE;
extern FARPROC GetProcAddress(HMODULE, const char *);

static FARPROC pfn_WinHttpPacJsWorkerMain;
static FARPROC pfn_WinHttpSetSecureLegacyServersAppCompat;
static FARPROC pfn_DllCanUnloadNow;
static FARPROC pfn_DllGetClassObject;
static FARPROC pfn_Private1;
static FARPROC pfn_SvchostPushServiceGlobals;
static FARPROC pfn_WinHttpAddRequestHeaders;
static FARPROC pfn_WinHttpAddRequestHeadersEx;
static FARPROC pfn_WinHttpAutoProxySvcMain;
static FARPROC pfn_WinHttpCheckPlatform;
static FARPROC pfn_WinHttpCloseHandle;
static FARPROC pfn_WinHttpConnect;
static FARPROC pfn_WinHttpConnectionDeletePolicyEntries;
static FARPROC pfn_WinHttpConnectionDeleteProxyInfo;
static FARPROC pfn_WinHttpConnectionFreeNameList;
static FARPROC pfn_WinHttpConnectionFreeProxyInfo;
static FARPROC pfn_WinHttpConnectionFreeProxyList;
static FARPROC pfn_WinHttpConnectionGetNameList;
static FARPROC pfn_WinHttpConnectionGetProxyInfo;
static FARPROC pfn_WinHttpConnectionGetProxyList;
static FARPROC pfn_WinHttpConnectionSetPolicyEntries;
static FARPROC pfn_WinHttpConnectionSetProxyInfo;
static FARPROC pfn_WinHttpConnectionUpdateIfIndexTable;
static FARPROC pfn_WinHttpCrackUrl;
static FARPROC pfn_WinHttpCreateProxyResolver;
static FARPROC pfn_WinHttpCreateUrl;
static FARPROC pfn_WinHttpDetectAutoProxyConfigUrl;
static FARPROC pfn_WinHttpFreeProxyResult;
static FARPROC pfn_WinHttpFreeProxyResultEx;
static FARPROC pfn_WinHttpFreeProxySettings;
static FARPROC pfn_WinHttpGetDefaultProxyConfiguration;
static FARPROC pfn_WinHttpGetIEProxyConfigForCurrentUser;
static FARPROC pfn_WinHttpGetProxyForUrl;
static FARPROC pfn_WinHttpGetProxyForUrlEx;
static FARPROC pfn_WinHttpGetProxyForUrlEx2;
static FARPROC pfn_WinHttpGetProxyForUrlHvsi;
static FARPROC pfn_WinHttpGetProxyResult;
static FARPROC pfn_WinHttpGetProxyResultEx;
static FARPROC pfn_WinHttpGetProxySettingsVersion;
static FARPROC pfn_WinHttpGetTunnelSocket;
static FARPROC pfn_WinHttpOpen;
static FARPROC pfn_WinHttpOpenRequest;
static FARPROC pfn_WinHttpProbeConnectivity;
static FARPROC pfn_WinHttpQueryAuthSchemes;
static FARPROC pfn_WinHttpQueryDataAvailable;
static FARPROC pfn_WinHttpQueryHeaders;
static FARPROC pfn_WinHttpQueryOption;
static FARPROC pfn_WinHttpReadData;
static FARPROC pfn_WinHttpReadProxySettings;
static FARPROC pfn_WinHttpReadProxySettingsHvsi;
static FARPROC pfn_WinHttpReceiveResponse;
static FARPROC pfn_WinHttpResetAutoProxy;
static FARPROC pfn_WinHttpSaveProxyCredentials;
static FARPROC pfn_WinHttpSendRequest;
static FARPROC pfn_WinHttpSetCredentials;
static FARPROC pfn_WinHttpSetDefaultProxyConfiguration;
static FARPROC pfn_WinHttpSetOption;
static FARPROC pfn_WinHttpSetProxySettingsPerUser;
static FARPROC pfn_WinHttpSetStatusCallback;
static FARPROC pfn_WinHttpSetTimeouts;
static FARPROC pfn_WinHttpTimeFromSystemTime;
static FARPROC pfn_WinHttpTimeToSystemTime;
static FARPROC pfn_WinHttpWebSocketClose;
static FARPROC pfn_WinHttpWebSocketCompleteUpgrade;
static FARPROC pfn_WinHttpWebSocketQueryCloseStatus;
static FARPROC pfn_WinHttpWebSocketReceive;
static FARPROC pfn_WinHttpWebSocketSend;
static FARPROC pfn_WinHttpWebSocketShutdown;
static FARPROC pfn_WinHttpWriteData;
static FARPROC pfn_WinHttpWriteProxySettings;

__declspec(dllexport) void *WinHttpPacJsWorkerMain() { return (void *)pfn_WinHttpPacJsWorkerMain(); }
__declspec(dllexport) void *WinHttpSetSecureLegacyServersAppCompat() { return (void *)pfn_WinHttpSetSecureLegacyServersAppCompat(); }
__declspec(dllexport) void *DllCanUnloadNow() { return (void *)pfn_DllCanUnloadNow(); }
__declspec(dllexport) void *DllGetClassObject() { return (void *)pfn_DllGetClassObject(); }
__declspec(dllexport) void *Private1() { return (void *)pfn_Private1(); }
__declspec(dllexport) void *SvchostPushServiceGlobals() { return (void *)pfn_SvchostPushServiceGlobals(); }
__declspec(dllexport) void *WinHttpAddRequestHeaders() { return (void *)pfn_WinHttpAddRequestHeaders(); }
__declspec(dllexport) void *WinHttpAddRequestHeadersEx() { return (void *)pfn_WinHttpAddRequestHeadersEx(); }
__declspec(dllexport) void *WinHttpAutoProxySvcMain() { return (void *)pfn_WinHttpAutoProxySvcMain(); }
__declspec(dllexport) void *WinHttpCheckPlatform() { return (void *)pfn_WinHttpCheckPlatform(); }
__declspec(dllexport) void *WinHttpCloseHandle() { return (void *)pfn_WinHttpCloseHandle(); }
__declspec(dllexport) void *WinHttpConnect() { return (void *)pfn_WinHttpConnect(); }
__declspec(dllexport) void *WinHttpConnectionDeletePolicyEntries() { return (void *)pfn_WinHttpConnectionDeletePolicyEntries(); }
__declspec(dllexport) void *WinHttpConnectionDeleteProxyInfo() { return (void *)pfn_WinHttpConnectionDeleteProxyInfo(); }
__declspec(dllexport) void *WinHttpConnectionFreeNameList() { return (void *)pfn_WinHttpConnectionFreeNameList(); }
__declspec(dllexport) void *WinHttpConnectionFreeProxyInfo() { return (void *)pfn_WinHttpConnectionFreeProxyInfo(); }
__declspec(dllexport) void *WinHttpConnectionFreeProxyList() { return (void *)pfn_WinHttpConnectionFreeProxyList(); }
__declspec(dllexport) void *WinHttpConnectionGetNameList() { return (void *)pfn_WinHttpConnectionGetNameList(); }
__declspec(dllexport) void *WinHttpConnectionGetProxyInfo() { return (void *)pfn_WinHttpConnectionGetProxyInfo(); }
__declspec(dllexport) void *WinHttpConnectionGetProxyList() { return (void *)pfn_WinHttpConnectionGetProxyList(); }
__declspec(dllexport) void *WinHttpConnectionSetPolicyEntries() { return (void *)pfn_WinHttpConnectionSetPolicyEntries(); }
__declspec(dllexport) void *WinHttpConnectionSetProxyInfo() { return (void *)pfn_WinHttpConnectionSetProxyInfo(); }
__declspec(dllexport) void *WinHttpConnectionUpdateIfIndexTable() { return (void *)pfn_WinHttpConnectionUpdateIfIndexTable(); }
__declspec(dllexport) void *WinHttpCrackUrl() { return (void *)pfn_WinHttpCrackUrl(); }
__declspec(dllexport) void *WinHttpCreateProxyResolver() { return (void *)pfn_WinHttpCreateProxyResolver(); }
__declspec(dllexport) void *WinHttpCreateUrl() { return (void *)pfn_WinHttpCreateUrl(); }
__declspec(dllexport) void *WinHttpDetectAutoProxyConfigUrl() { return (void *)pfn_WinHttpDetectAutoProxyConfigUrl(); }
__declspec(dllexport) void *WinHttpFreeProxyResult() { return (void *)pfn_WinHttpFreeProxyResult(); }
__declspec(dllexport) void *WinHttpFreeProxyResultEx() { return (void *)pfn_WinHttpFreeProxyResultEx(); }
__declspec(dllexport) void *WinHttpFreeProxySettings() { return (void *)pfn_WinHttpFreeProxySettings(); }
__declspec(dllexport) void *WinHttpGetDefaultProxyConfiguration() { return (void *)pfn_WinHttpGetDefaultProxyConfiguration(); }
__declspec(dllexport) void *WinHttpGetIEProxyConfigForCurrentUser() { return (void *)pfn_WinHttpGetIEProxyConfigForCurrentUser(); }
__declspec(dllexport) void *WinHttpGetProxyForUrl() { return (void *)pfn_WinHttpGetProxyForUrl(); }
__declspec(dllexport) void *WinHttpGetProxyForUrlEx() { return (void *)pfn_WinHttpGetProxyForUrlEx(); }
__declspec(dllexport) void *WinHttpGetProxyForUrlEx2() { return (void *)pfn_WinHttpGetProxyForUrlEx2(); }
__declspec(dllexport) void *WinHttpGetProxyForUrlHvsi() { return (void *)pfn_WinHttpGetProxyForUrlHvsi(); }
__declspec(dllexport) void *WinHttpGetProxyResult() { return (void *)pfn_WinHttpGetProxyResult(); }
__declspec(dllexport) void *WinHttpGetProxyResultEx() { return (void *)pfn_WinHttpGetProxyResultEx(); }
__declspec(dllexport) void *WinHttpGetProxySettingsVersion() { return (void *)pfn_WinHttpGetProxySettingsVersion(); }
__declspec(dllexport) void *WinHttpGetTunnelSocket() { return (void *)pfn_WinHttpGetTunnelSocket(); }
__declspec(dllexport) void *WinHttpOpen() { return (void *)pfn_WinHttpOpen(); }
__declspec(dllexport) void *WinHttpOpenRequest() { return (void *)pfn_WinHttpOpenRequest(); }
__declspec(dllexport) void *WinHttpProbeConnectivity() { return (void *)pfn_WinHttpProbeConnectivity(); }
__declspec(dllexport) void *WinHttpQueryAuthSchemes() { return (void *)pfn_WinHttpQueryAuthSchemes(); }
__declspec(dllexport) void *WinHttpQueryDataAvailable() { return (void *)pfn_WinHttpQueryDataAvailable(); }
__declspec(dllexport) void *WinHttpQueryHeaders() { return (void *)pfn_WinHttpQueryHeaders(); }
__declspec(dllexport) void *WinHttpQueryOption() { return (void *)pfn_WinHttpQueryOption(); }
__declspec(dllexport) void *WinHttpReadData() { return (void *)pfn_WinHttpReadData(); }
__declspec(dllexport) void *WinHttpReadProxySettings() { return (void *)pfn_WinHttpReadProxySettings(); }
__declspec(dllexport) void *WinHttpReadProxySettingsHvsi() { return (void *)pfn_WinHttpReadProxySettingsHvsi(); }
__declspec(dllexport) void *WinHttpReceiveResponse() { return (void *)pfn_WinHttpReceiveResponse(); }
__declspec(dllexport) void *WinHttpResetAutoProxy() { return (void *)pfn_WinHttpResetAutoProxy(); }
__declspec(dllexport) void *WinHttpSaveProxyCredentials() { return (void *)pfn_WinHttpSaveProxyCredentials(); }
__declspec(dllexport) void *WinHttpSendRequest() { return (void *)pfn_WinHttpSendRequest(); }
__declspec(dllexport) void *WinHttpSetCredentials() { return (void *)pfn_WinHttpSetCredentials(); }
__declspec(dllexport) void *WinHttpSetDefaultProxyConfiguration() { return (void *)pfn_WinHttpSetDefaultProxyConfiguration(); }
__declspec(dllexport) void *WinHttpSetOption() { return (void *)pfn_WinHttpSetOption(); }
__declspec(dllexport) void *WinHttpSetProxySettingsPerUser() { return (void *)pfn_WinHttpSetProxySettingsPerUser(); }
__declspec(dllexport) void *WinHttpSetStatusCallback() { return (void *)pfn_WinHttpSetStatusCallback(); }
__declspec(dllexport) void *WinHttpSetTimeouts() { return (void *)pfn_WinHttpSetTimeouts(); }
__declspec(dllexport) void *WinHttpTimeFromSystemTime() { return (void *)pfn_WinHttpTimeFromSystemTime(); }
__declspec(dllexport) void *WinHttpTimeToSystemTime() { return (void *)pfn_WinHttpTimeToSystemTime(); }
__declspec(dllexport) void *WinHttpWebSocketClose() { return (void *)pfn_WinHttpWebSocketClose(); }
__declspec(dllexport) void *WinHttpWebSocketCompleteUpgrade() { return (void *)pfn_WinHttpWebSocketCompleteUpgrade(); }
__declspec(dllexport) void *WinHttpWebSocketQueryCloseStatus() { return (void *)pfn_WinHttpWebSocketQueryCloseStatus(); }
__declspec(dllexport) void *WinHttpWebSocketReceive() { return (void *)pfn_WinHttpWebSocketReceive(); }
__declspec(dllexport) void *WinHttpWebSocketSend() { return (void *)pfn_WinHttpWebSocketSend(); }
__declspec(dllexport) void *WinHttpWebSocketShutdown() { return (void *)pfn_WinHttpWebSocketShutdown(); }
__declspec(dllexport) void *WinHttpWriteData() { return (void *)pfn_WinHttpWriteData(); }
__declspec(dllexport) void *WinHttpWriteProxySettings() { return (void *)pfn_WinHttpWriteProxySettings(); }

void proxy_importFunctions(void *hModule) {
  pfn_WinHttpPacJsWorkerMain = GetProcAddress(hModule, "WinHttpPacJsWorkerMain");
  pfn_WinHttpSetSecureLegacyServersAppCompat = GetProcAddress(hModule, "WinHttpSetSecureLegacyServersAppCompat");
  pfn_DllCanUnloadNow = GetProcAddress(hModule, "DllCanUnloadNow");
  pfn_DllGetClassObject = GetProcAddress(hModule, "DllGetClassObject");
  pfn_Private1 = GetProcAddress(hModule, "Private1");
  pfn_SvchostPushServiceGlobals = GetProcAddress(hModule, "SvchostPushServiceGlobals");
  pfn_WinHttpAddRequestHeaders = GetProcAddress(hModule, "WinHttpAddRequestHeaders");
  pfn_WinHttpAddRequestHeadersEx = GetProcAddress(hModule, "WinHttpAddRequestHeadersEx");
  pfn_WinHttpAutoProxySvcMain = GetProcAddress(hModule, "WinHttpAutoProxySvcMain");
  pfn_WinHttpCheckPlatform = GetProcAddress(hModule, "WinHttpCheckPlatform");
  pfn_WinHttpCloseHandle = GetProcAddress(hModule, "WinHttpCloseHandle");
  pfn_WinHttpConnect = GetProcAddress(hModule, "WinHttpConnect");
  pfn_WinHttpConnectionDeletePolicyEntries = GetProcAddress(hModule, "WinHttpConnectionDeletePolicyEntries");
  pfn_WinHttpConnectionDeleteProxyInfo = GetProcAddress(hModule, "WinHttpConnectionDeleteProxyInfo");
  pfn_WinHttpConnectionFreeNameList = GetProcAddress(hModule, "WinHttpConnectionFreeNameList");
  pfn_WinHttpConnectionFreeProxyInfo = GetProcAddress(hModule, "WinHttpConnectionFreeProxyInfo");
  pfn_WinHttpConnectionFreeProxyList = GetProcAddress(hModule, "WinHttpConnectionFreeProxyList");
  pfn_WinHttpConnectionGetNameList = GetProcAddress(hModule, "WinHttpConnectionGetNameList");
  pfn_WinHttpConnectionGetProxyInfo = GetProcAddress(hModule, "WinHttpConnectionGetProxyInfo");
  pfn_WinHttpConnectionGetProxyList = GetProcAddress(hModule, "WinHttpConnectionGetProxyList");
  pfn_WinHttpConnectionSetPolicyEntries = GetProcAddress(hModule, "WinHttpConnectionSetPolicyEntries");
  pfn_WinHttpConnectionSetProxyInfo = GetProcAddress(hModule, "WinHttpConnectionSetProxyInfo");
  pfn_WinHttpConnectionUpdateIfIndexTable = GetProcAddress(hModule, "WinHttpConnectionUpdateIfIndexTable");
  pfn_WinHttpCrackUrl = GetProcAddress(hModule, "WinHttpCrackUrl");
  pfn_WinHttpCreateProxyResolver = GetProcAddress(hModule, "WinHttpCreateProxyResolver");
  pfn_WinHttpCreateUrl = GetProcAddress(hModule, "WinHttpCreateUrl");
  pfn_WinHttpDetectAutoProxyConfigUrl = GetProcAddress(hModule, "WinHttpDetectAutoProxyConfigUrl");
  pfn_WinHttpFreeProxyResult = GetProcAddress(hModule, "WinHttpFreeProxyResult");
  pfn_WinHttpFreeProxyResultEx = GetProcAddress(hModule, "WinHttpFreeProxyResultEx");
  pfn_WinHttpFreeProxySettings = GetProcAddress(hModule, "WinHttpFreeProxySettings");
  pfn_WinHttpGetDefaultProxyConfiguration = GetProcAddress(hModule, "WinHttpGetDefaultProxyConfiguration");
  pfn_WinHttpGetIEProxyConfigForCurrentUser = GetProcAddress(hModule, "WinHttpGetIEProxyConfigForCurrentUser");
  pfn_WinHttpGetProxyForUrl = GetProcAddress(hModule, "WinHttpGetProxyForUrl");
  pfn_WinHttpGetProxyForUrlEx = GetProcAddress(hModule, "WinHttpGetProxyForUrlEx");
  pfn_WinHttpGetProxyForUrlEx2 = GetProcAddress(hModule, "WinHttpGetProxyForUrlEx2");
  pfn_WinHttpGetProxyForUrlHvsi = GetProcAddress(hModule, "WinHttpGetProxyForUrlHvsi");
  pfn_WinHttpGetProxyResult = GetProcAddress(hModule, "WinHttpGetProxyResult");
  pfn_WinHttpGetProxyResultEx = GetProcAddress(hModule, "WinHttpGetProxyResultEx");
  pfn_WinHttpGetProxySettingsVersion = GetProcAddress(hModule, "WinHttpGetProxySettingsVersion");
  pfn_WinHttpGetTunnelSocket = GetProcAddress(hModule, "WinHttpGetTunnelSocket");
  pfn_WinHttpOpen = GetProcAddress(hModule, "WinHttpOpen");
  pfn_WinHttpOpenRequest = GetProcAddress(hModule, "WinHttpOpenRequest");
  pfn_WinHttpProbeConnectivity = GetProcAddress(hModule, "WinHttpProbeConnectivity");
  pfn_WinHttpQueryAuthSchemes = GetProcAddress(hModule, "WinHttpQueryAuthSchemes");
  pfn_WinHttpQueryDataAvailable = GetProcAddress(hModule, "WinHttpQueryDataAvailable");
  pfn_WinHttpQueryHeaders = GetProcAddress(hModule, "WinHttpQueryHeaders");
  pfn_WinHttpQueryOption = GetProcAddress(hModule, "WinHttpQueryOption");
  pfn_WinHttpReadData = GetProcAddress(hModule, "WinHttpReadData");
  pfn_WinHttpReadProxySettings = GetProcAddress(hModule, "WinHttpReadProxySettings");
  pfn_WinHttpReadProxySettingsHvsi = GetProcAddress(hModule, "WinHttpReadProxySettingsHvsi");
  pfn_WinHttpReceiveResponse = GetProcAddress(hModule, "WinHttpReceiveResponse");
  pfn_WinHttpResetAutoProxy = GetProcAddress(hModule, "WinHttpResetAutoProxy");
  pfn_WinHttpSaveProxyCredentials = GetProcAddress(hModule, "WinHttpSaveProxyCredentials");
  pfn_WinHttpSendRequest = GetProcAddress(hModule, "WinHttpSendRequest");
  pfn_WinHttpSetCredentials = GetProcAddress(hModule, "WinHttpSetCredentials");
  pfn_WinHttpSetDefaultProxyConfiguration = GetProcAddress(hModule, "WinHttpSetDefaultProxyConfiguration");
  pfn_WinHttpSetOption = GetProcAddress(hModule, "WinHttpSetOption");
  pfn_WinHttpSetProxySettingsPerUser = GetProcAddress(hModule, "WinHttpSetProxySettingsPerUser");
  pfn_WinHttpSetStatusCallback = GetProcAddress(hModule, "WinHttpSetStatusCallback");
  pfn_WinHttpSetTimeouts = GetProcAddress(hModule, "WinHttpSetTimeouts");
  pfn_WinHttpTimeFromSystemTime = GetProcAddress(hModule, "WinHttpTimeFromSystemTime");
  pfn_WinHttpTimeToSystemTime = GetProcAddress(hModule, "WinHttpTimeToSystemTime");
  pfn_WinHttpWebSocketClose = GetProcAddress(hModule, "WinHttpWebSocketClose");
  pfn_WinHttpWebSocketCompleteUpgrade = GetProcAddress(hModule, "WinHttpWebSocketCompleteUpgrade");
  pfn_WinHttpWebSocketQueryCloseStatus = GetProcAddress(hModule, "WinHttpWebSocketQueryCloseStatus");
  pfn_WinHttpWebSocketReceive = GetProcAddress(hModule, "WinHttpWebSocketReceive");
  pfn_WinHttpWebSocketSend = GetProcAddress(hModule, "WinHttpWebSocketSend");
  pfn_WinHttpWebSocketShutdown = GetProcAddress(hModule, "WinHttpWebSocketShutdown");
  pfn_WinHttpWriteData = GetProcAddress(hModule, "WinHttpWriteData");
  pfn_WinHttpWriteProxySettings = GetProcAddress(hModule, "WinHttpWriteProxySettings");
}
